<?php
ini_set('display_errors', '1');
error_reporting(E_ALL);

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

// Change this before uploading to production.
define('SETUP_KEY', 'paul');

define('APP_NAME', 'Hotel Victoria');

define('SETUP_SCHEMA_FILE', __DIR__ . '/schema.sql');
define('SETUP_SQLITE_SCHEMA_FILE', __DIR__ . '/schema-sqlite.sql');

function h($value) {
    return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
}

function requestValue($key, $default = '') {
    return $_POST[$key] ?? $_GET[$key] ?? $default;
}

function isAuthorized() {
    $providedKey = trim((string) requestValue('setup_key', ''));
    return $providexdKey !== '' && hash_equals(SETUP_KEY, $providedKey);
}

function pageHeader($title) {   
    echo '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">';
    echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
    echo '<title>' . h($title) . '</title>';
    echo '<style>';
    echo 'body{font-family:Arial,sans-serif;background:#f4f6f8;margin:0;padding:24px;color:#1f2937}';
    echo '.wrap{max-width:900px;margin:0 auto}';
    echo '.card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:24px;box-shadow:0 8px 28px rgba(15,23,42,.08)}';
    echo 'h1{margin:0 0 12px;font-size:28px}h2{margin:24px 0 12px;font-size:18px}p{line-height:1.6}';
    echo '.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}';
    echo '.grid-1{display:grid;grid-template-columns:1fr;gap:12px}';
    echo 'label{font-weight:700;display:block;margin-bottom:6px}input{width:100%;padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px;font-size:14px;box-sizing:border-box}';
    echo '.hint{font-size:13px;color:#6b7280;margin-top:4px}';
    echo '.btn{display:inline-block;background:#0f766e;color:#fff;border:0;border-radius:8px;padding:12px 16px;font-weight:700;cursor:pointer}';
    echo '.btn.secondary{background:#64748b}.btn.danger{background:#b45309}';
    echo '.alert{padding:14px 16px;border-radius:10px;margin:14px 0}.info{background:#eff6ff;border:1px solid #bfdbfe}.success{background:#ecfdf5;border:1px solid #a7f3d0}.error{background:#fef2f2;border:1px solid #fecaca}';
    echo 'code,pre{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:2px 6px}pre{padding:12px;overflow:auto}';
    echo '.section{border-top:1px solid #e5e7eb;margin-top:20px;padding-top:20px}';
    echo '.muted{color:#6b7280}ul{line-height:1.7}';
    echo '</style></head><body><div class="wrap"><div class="card">';
    echo '<h1>' . h($title) . '</h1>';
}

function pageFooter() {
    echo '</div></div></body></html>';
}

function connectMysql($host, $user, $pass, $dbName = null) {
    if ($dbName === null || $dbName === '') {
        return new mysqli($host, $user, $pass);
    }

    return new mysqli($host, $user, $pass, $dbName);
}

function buildServerConfig(array $data, $baseUrl) {
    $lines = [];
    $lines[] = '<?php';
    $lines[] = '';
    $lines[] = '// Generated by setup.php';
    $lines[] = 'if (!defined(\'DB_HOST\')) define(\'DB_HOST\', ' . var_export($data['db_host'], true) . ');';
    $lines[] = 'if (!defined(\'DB_USER\')) define(\'DB_USER\', ' . var_export($data['db_user'], true) . ');';
    $lines[] = 'if (!defined(\'DB_PASS\')) define(\'DB_PASS\', ' . var_export($data['db_pass'], true) . ');';
    $lines[] = 'if (!defined(\'DB_NAME\')) define(\'DB_NAME\', ' . var_export($data['db_name'], true) . ');';
    $lines[] = 'if (!defined(\'CONTACT_TYPES_DB_FILE\')) define(\'CONTACT_TYPES_DB_FILE\', ' . var_export($data['contact_types_db_file'], true) . ');';
    $lines[] = 'if (!defined(\'BASE_URL\')) define(\'BASE_URL\', ' . var_export($baseUrl, true) . ');';
    $lines[] = 'if (!defined(\'BACKEND_URL\')) define(\'BACKEND_URL\', BASE_URL . \'back-end/\');';
    $lines[] = 'if (!defined(\'FRONTEND_URL\')) define(\'FRONTEND_URL\', BASE_URL . \'front-end/\');';
    $lines[] = 'if (!defined(\'PAGES_URL\')) define(\'PAGES_URL\', FRONTEND_URL . \'Pages/\');';
    $lines[] = '';
    return implode(PHP_EOL, $lines) . PHP_EOL;
}

function extractCreateStatements($schemaSql) {
    $statements = preg_split('/;\s*(?:\r?\n|$)/', $schemaSql);
    $createStatements = [];

    foreach ($statements as $statement) {
        $trimmed = trim($statement);
        if ($trimmed === '') {
            continue;
        }

        if (preg_match('/^(CREATE\s+TABLE|CREATE\s+INDEX|ALTER\s+TABLE)/i', $trimmed)) {
            $createStatements[] = $trimmed;
        }
    }

    return $createStatements;
}

function runCreateStatements(mysqli $conn, array $statements) {
    $executed = 0;
    foreach ($statements as $statement) {
        $conn->query($statement);
        $executed++;
    }
    return $executed;
}

function roomsSampleData() {
    return [
        ['101', 'twin', 2, 320.00, 'Standard twin room with two separate beds, free Wi-Fi, TV, air conditioning, minibar'],
        ['102', 'twin', 2, 320.00, 'Standard twin room with two separate beds, free Wi-Fi, TV, air conditioning, minibar'],
        ['103', 'twin', 2, 320.00, 'Standard twin room with two separate beds, free Wi-Fi, TV, air conditioning, minibar'],
        ['104', 'twin', 2, 320.00, 'Standard twin room with two separate beds, free Wi-Fi, TV, air conditioning, minibar'],
        ['201', 'double', 2, 300.00, 'Standard double room with double bed, free Wi-Fi, TV, air conditioning, minibar'],
        ['202', 'double', 2, 300.00, 'Standard double room with double bed, free Wi-Fi, TV, air conditioning, minibar'],
        ['203', 'double', 2, 300.00, 'Standard double room with double bed, free Wi-Fi, TV, air conditioning, minibar'],
        ['204', 'double', 2, 300.00, 'Standard double room with double bed, free Wi-Fi, TV, air conditioning, minibar'],
        ['301', 'apartament', 4, 450.00, 'Spacious apartment for 4 guests, safe, TV, air conditioning, minibar, fridge, free Wi-Fi'],
        ['302', 'apartament', 4, 450.00, 'Spacious apartment for 4 guests, safe, TV, air conditioning, minibar, fridge, free Wi-Fi'],
        ['303', 'apartament', 4, 450.00, 'Spacious apartment for 4 guests, safe, TV, air conditioning, minibar, fridge, free Wi-Fi'],
        ['401', 'deluxe', 4, 650.00, 'Premium deluxe apartment with balcony, jacuzzi, double bed, safe, TV, air conditioning, minibar, fridge, breakfast included, free Wi-Fi'],
        ['402', 'deluxe', 4, 650.00, 'Premium deluxe apartment with balcony, jacuzzi, double bed, safe, TV, air conditioning, minibar, fridge, breakfast included, free Wi-Fi'],
    ];
}

function ensureSampleRooms(mysqli $conn) {
    $countResult = $conn->query('SELECT COUNT(*) AS total FROM rooms');
    $countRow = $countResult->fetch_assoc();
    if ((int) ($countRow['total'] ?? 0) > 0) {
        return 0;
    }

    $stmt = $conn->prepare('INSERT INTO rooms (room_number, room_type, capacity, price_per_night, description, status, created_at) VALUES (?, ?, ?, ?, ?, \'available\', NOW())');
    $inserted = 0;

    foreach (roomsSampleData() as $room) {
        $stmt->bind_param('ssids', $room[0], $room[1], $room[2], $room[3], $room[4]);
        $stmt->execute();
        $inserted++;
    }

    $stmt->close();
    return $inserted;
}

function ensureAdminUser(mysqli $conn, $username, $email, $password, $fullName) {
    $check = $conn->prepare('SELECT id FROM users WHERE username = ? OR email = ? LIMIT 1');
    $check->bind_param('ss', $username, $email);
    $check->execute();
    $exists = $check->get_result()->num_rows > 0;
    $check->close();

    if ($exists) {
        return 'Admin user already exists; skipping creation.';
    }

    $hash = password_hash($password, PASSWORD_BCRYPT);
    $stmt = $conn->prepare('INSERT INTO users (username, email, password, full_name, role, created_at, updated_at) VALUES (?, ?, ?, ?, \'admin\', NOW(), NOW())');
    $stmt->bind_param('ssss', $username, $email, $hash, $fullName);
    $stmt->execute();
    $stmt->close();

    return 'Admin user created successfully.';
}

function createDatabaseIfNeeded(mysqli $serverConn, $dbName) {
    $safeName = str_replace('`', '``', $dbName);
    $serverConn->query("CREATE DATABASE IF NOT EXISTS `{$safeName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
}

function maybeCreateSqliteSchema($sqliteFile) {
    if ($sqliteFile === '') {
        return 'SQLite file path not provided; skipped.';
    }

    if (!in_array('sqlite', PDO::getAvailableDrivers(), true)) {
        return 'SQLite PDO driver is not available on this server; skipped.';
    }

    $sqliteDir = dirname($sqliteFile);
    if (!is_dir($sqliteDir) && !@mkdir($sqliteDir, 0775, true) && !is_dir($sqliteDir)) {
        return 'Could not create the SQLite directory; skipped.';
    }

    if (!file_exists($sqliteFile)) {
        @touch($sqliteFile);
    }

    try {
        $sqlitePdo = new PDO(
            'sqlite:' . $sqliteFile,
            null,
            null,
            [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]
        );
    } catch (Throwable $e) {
        return 'Could not open the SQLite database; skipped.';
    }

    if (!file_exists(SETUP_SQLITE_SCHEMA_FILE)) {
        return 'SQLite schema file not found; skipped.';
    }

    $schemaSql = file_get_contents(SETUP_SQLITE_SCHEMA_FILE);
    $statements = preg_split('/;\s*(?:\r?\n|$)/', $schemaSql);
    foreach ($statements as $statement) {
        $trimmed = trim($statement);
        if ($trimmed !== '') {
            $sqlitePdo->exec($trimmed);
        }
    }

    @chmod($sqliteDir, 0775);
    @chmod($sqliteFile, 0664);

    return 'SQLite schema checked successfully.';
}

function handleSetup(array $input) {
    $dbHost = trim((string) ($input['db_host'] ?? ''));
    $dbUser = trim((string) ($input['db_user'] ?? ''));
    $dbPass = (string) ($input['db_pass'] ?? '');
    $dbName = trim((string) ($input['db_name'] ?? ''));
    $adminUsername = trim((string) ($input['admin_username'] ?? ''));
    $adminEmail = trim((string) ($input['admin_email'] ?? ''));
    $adminPassword = (string) ($input['admin_password'] ?? '');
    $adminFullName = trim((string) ($input['admin_fullname'] ?? ''));
    $writeConfig = !empty($input['write_config']);
    $onlySqlite = !empty($input['only_sqlite']);

    if (!$onlySqlite) {
        if ($dbHost === '' || $dbUser === '' || $dbName === '' || $adminUsername === '' || $adminEmail === '' || $adminPassword === '' || $adminFullName === '') {
            return ['ok' => false, 'message' => 'All required fields must be completed.'];
        }
    }

    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
        return ['ok' => false, 'message' => 'The admin email address is invalid.'];
    }

    if (strlen($adminPassword) < 8) {
        return ['ok' => false, 'message' => 'The admin password must be at least 8 characters long.'];
    }

    try {
        $sqliteDbFile = __DIR__ . '/contact-types.sqlite';

        if ($onlySqlite) {
            // Only create/check the SQLite DB (MySQL already configured)
            $executedStatements = 0;
            $insertedRooms = 0;
            $adminMessage = 'Skipped MySQL operations (only SQLite requested).';
            $sqliteMessage = maybeCreateSqliteSchema($sqliteDbFile);
        } else {
            $serverConn = connectMysql($dbHost, $dbUser, $dbPass);
            createDatabaseIfNeeded($serverConn, $dbName);
            $serverConn->select_db($dbName);

            if (!file_exists(SETUP_SCHEMA_FILE)) {
                return ['ok' => false, 'message' => 'schema.sql was not found next to setup.php.'];
            }

            $schemaSql = file_get_contents(SETUP_SCHEMA_FILE);
            $createStatements = extractCreateStatements($schemaSql);
            $executedStatements = runCreateStatements($serverConn, $createStatements);
            $insertedRooms = ensureSampleRooms($serverConn);
            $adminMessage = ensureAdminUser($serverConn, $adminUsername, $adminEmail, $adminPassword, $adminFullName);
            $sqliteMessage = maybeCreateSqliteSchema($sqliteDbFile);
        }

        $baseUrl = rtrim(sprintf(
            '%s://%s%s/',
            (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http',
            $_SERVER['HTTP_HOST'] ?? 'localhost',
            dirname(dirname($_SERVER['SCRIPT_NAME'] ?? '/'))
        ), '/') . '/';

        $configMessage = 'server-config.php was not written.';
        if ($writeConfig) {
            $configPath = __DIR__ . '/server-config.php';
            $configData = [
                'db_host' => $dbHost,
                'db_user' => $dbUser,
                'db_pass' => $dbPass,
                'db_name' => $dbName,
                'contact_types_db_file' => $sqliteDbFile,
            ];

            $written = @file_put_contents($configPath, buildServerConfig($configData, $baseUrl));
            if ($written === false) {
                $configMessage = 'Could not write server-config.php automatically. Copy the settings from this page into back-end/server-config.php manually.';
            } else {
                $configMessage = 'server-config.php created successfully.';
            }
        }

        $serverConn->close();

        return [
            'ok' => true,
            'message' => 'Setup completed successfully.',
            'details' => [
                'Database host' => $dbHost,
                'Database name' => $dbName,
                'Database user' => $dbUser,
                'Create statements executed' => (string) $executedStatements,
                'Sample rooms inserted' => (string) $insertedRooms,
                'Admin status' => $adminMessage,
                'SQLite status' => $sqliteMessage,
                'Production config' => $configMessage,
                'Base URL' => $baseUrl,
            ],
            'baseUrl' => $baseUrl,
            'db' => [
                'host' => $dbHost,
                'user' => $dbUser,
                'pass' => $dbPass,
                'name' => $dbName,
            ],
            'sqlite_file' => $sqliteDbFile,
        ];
    } catch (Throwable $e) {
        return ['ok' => false, 'message' => 'Setup failed: ' . $e->getMessage()];
    }
}

$authorized = isAuthorized();
$submitted = $authorized && !empty($_POST['do_setup']);
$result = null;
if ($submitted) {
    $result = handleSetup($_POST);
}

pageHeader(APP_NAME . ' setup');

if (!$authorized) {
    echo '<div class="alert error">Enter the setup key to continue.</div>';
    echo '<form method="post" class="grid-1">';
    echo '<div><label for="setup_key">Setup key</label><input id="setup_key" name="setup_key" type="password" required></div>';
    echo '<button class="btn" type="submit">Authorize</button>';
    echo '</form>';
    echo '<div class="section"><p class="muted">Change SETUP_KEY in setup.php before uploading this file to production, then delete setup.php after the setup is complete.</p></div>';
    pageFooter();
    exit;
}

if ($result && !$result['ok']) {
    echo '<div class="alert error">' . h($result['message']) . '</div>';
}

if ($result && $result['ok']) {
    echo '<div class="alert success"><strong>' . h($result['message']) . '</strong></div>';
    echo '<div class="section"><h2>Summary</h2><ul>';
    foreach ($result['details'] as $label => $value) {
        echo '<li><strong>' . h($label) . ':</strong> ' . h($value) . '</li>';
    }
    echo '</ul></div>';
    echo '<div class="alert info"><strong>Next step:</strong> open the application and verify that config.php is loading <code>back-end/server-config.php</code>. Then delete setup.php from the server.</div>';
    echo '<div class="section"><h2>Generated server-config.php values</h2>';
    echo '<p class="muted">If automatic writing failed, create <code>back-end/server-config.php</code> with these values:</p>';
    echo '<pre>' . h(buildServerConfig([
        'db_host' => $result['db']['host'],
        'db_user' => $result['db']['user'],
        'db_pass' => $result['db']['pass'],
        'db_name' => $result['db']['name'],
        'contact_types_db_file' => $result['sqlite_file'],
    ], $result['baseUrl'])) . '</pre>';
    pageFooter();
    exit;
}

echo '<div class="alert info">This page creates the MySQL database, schema, sample rooms, and an initial admin account. It also creates the local SQLite database used for contact message types and can write a separate production config file that the app will use on the server.</div>';

echo '<form method="post">';
echo '<input type="hidden" name="setup_key" value="' . h(requestValue('setup_key')) . '">';
echo '<input type="hidden" name="do_setup" value="1">';

echo '<div class="section"><h2>MySQL settings</h2><div class="grid">';
echo '<div><label for="db_host">Host</label><input id="db_host" name="db_host" value="' . h(requestValue('db_host', 'localhost')) . '" required><div class="hint">Usually localhost on shared hosting.</div></div>';
echo '<div><label for="db_name">Database name</label><input id="db_name" name="db_name" value="' . h(requestValue('db_name', 'hotel_victoria')) . '" required><div class="hint">Will be created if your account has permission.</div></div>';
echo '<div><label for="db_user">Database user</label><input id="db_user" name="db_user" value="' . h(requestValue('db_user')) . '" required></div>';
echo '<div><label for="db_pass">Database password</label><input id="db_pass" name="db_pass" type="password" value="' . h(requestValue('db_pass')) . '"></div>';
echo '</div></div>';

echo '<div class="section"><h2>Admin account</h2><div class="grid">';
echo '<div><label for="admin_username">Username</label><input id="admin_username" name="admin_username" value="' . h(requestValue('admin_username', 'admin')) . '" required></div>';
echo '<div><label for="admin_email">Email</label><input id="admin_email" name="admin_email" type="email" value="' . h(requestValue('admin_email')) . '" required></div>';
echo '<div><label for="admin_password">Password</label><input id="admin_password" name="admin_password" type="password" minlength="8" required></div>';
echo '<div><label for="admin_fullname">Full name</label><input id="admin_fullname" name="admin_fullname" value="' . h(requestValue('admin_fullname', 'Administrator')) . '" required></div>';
echo '</div></div>';

echo '<div class="section"><label><input type="checkbox" name="only_sqlite" value="1"' . (requestValue('only_sqlite') ? ' checked' : '') . '> Only create SQLite contact types database (skip MySQL operations)</label><p class="muted">Use this if your MySQL database is already set up and you only need the local contact-types SQLite DB.</p></div>';

echo '<div class="section"><h2>SQLite contact types</h2><p class="muted">No username, password, or database name is required here. Setup will create <code>back-end/contact-types.sqlite</code> automatically, load the contact message types into it, and apply writable permissions if the server allows it.</p></div>';

echo '<div class="section"><h2>Output</h2><label><input type="checkbox" name="write_config" value="1" checked> Write back-end/server-config.php so the app can use the production settings</label><p class="muted">Leave this checked unless you want to copy the file manually.</p></div>';

echo '<div class="section"><button class="btn" type="submit">Create database, tables, and admin</button></div>';
echo '</form>';

echo '<div class="section"><h2>What this will create</h2><ul><li>MySQL database and tables from schema.sql</li><li>13 sample rooms if the rooms table is empty</li><li>An admin account with the details you enter</li><li>SQLite contact types database at back-end/contact-types.sqlite</li><li>Writable file permissions for the SQLite database where the server permits it</li><li>Optional back-end/server-config.php with production credentials</li></ul></div>';

echo '<div class="section"><p class="muted">After the setup succeeds, remove setup.php from the server.</p></div>';

pageFooter();
