package org.example.laboratorGUI.utils.event;

public enum EntityChangeEventType {
    USER_ADDED, USER_UPDATED, USER_REMOVED,
    FRIENDSHIP_SENT, FRIENDSHIP_ACCEPTED, FRIENDSHIP_REJECTED, FRIENDSHIP_REMOVED,
    MESSAGE_RECEIVED,
    EVENT_ADDED, EVENT_REMOVED, EVENT_FINISHED
}
