<?php

// Generated by setup.php
if (!defined('DB_HOST')) define('DB_HOST', 'localhost');
if (!defined('DB_USER')) define('DB_USER', 'root');
if (!defined('DB_PASS')) define('DB_PASS', '');
if (!defined('DB_NAME')) define('DB_NAME', 'hotel_victoria');
if (!defined('CONTACT_TYPES_DB_FILE')) define('CONTACT_TYPES_DB_FILE', 'C:\\xampp\\htdocs\\hotel-victoria\\back-end/contact-types.sqlite');
if (!defined('BASE_URL')) define('BASE_URL', 'http://localhost/hotel-victoria/');
if (!defined('BACKEND_URL')) define('BACKEND_URL', BASE_URL . 'back-end/');
if (!defined('FRONTEND_URL')) define('FRONTEND_URL', BASE_URL . 'front-end/');
if (!defined('PAGES_URL')) define('PAGES_URL', FRONTEND_URL . 'Pages/');

